Update Jenkinsfile

diff --git a/src/cart/Jenkinsfile b/src/cart/Jenkinsfile
--- a/src/cart/Jenkinsfile
+++ b/src/cart/Jenkinsfile
@@ -3,16 +3,12 @@ pipeline {
 
     environment {
 
-        AWS_REGION = "ap-south-1"
-        AWS_ACCOUNT_ID = "<AWS-ACCOUNT-ID>" #replace your aws account id
+        AWS_REGION = "us-east-1"
 
-        ECR_REPO = "open-telemetry-registry" #replace you ECR repo name
+        PUBLIC_ECR_URI = "public.ecr.aws/q2a1e2p7/open-telemetry-demo"
 
         IMAGE_NAME = "cart"
-
-        IMAGE_TAG = "${BUILD_NUMBER}"
-
-        ECR_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
+        IMAGE_TAG = "${IMAGE_NAME}-${BUILD_NUMBER}"
 
         K8S_DEPLOYMENT = "opentelemetry-demo-cartservice"
         NAMESPACE = "default"
@@ -23,7 +19,7 @@ pipeline {
         stage('Checkout') {
             steps {
                 git branch: 'main',
-                url: 'https://github.com/Astronomy-NextGenIT/Open-telemetry-Mono-repo.git'
+                    url: 'https://github.com/Astronomy-NextGenIT/Open-telemetry-Mono-repo.git'
             }
         }
 
@@ -37,15 +33,14 @@ pipeline {
             }
         }
 
-        stage('ECR Login') {
+        stage('Login Public ECR') {
             steps {
                 sh '''
-                aws ecr get-login-password \
+                aws ecr-public get-login-password \
                 --region ${AWS_REGION} | \
                 docker login \
                 --username AWS \
-                --password-stdin \
-                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+                --password-stdin public.ecr.aws
                 '''
             }
         }
@@ -65,15 +60,20 @@ pipeline {
                 sh '''
                 docker tag \
                 ${IMAGE_NAME}:${IMAGE_TAG} \
-                ${ECR_URI}:${IMAGE_TAG}
+                ${PUBLIC_ECR_URI}:${IMAGE_TAG}
+
+                docker tag \
+                ${IMAGE_NAME}:${IMAGE_TAG} \
+                ${PUBLIC_ECR_URI}:${IMAGE_NAME}-latest
                 '''
             }
         }
 
-        stage('Push Image To ECR') {
+        stage('Push Image To Public ECR') {
             steps {
                 sh '''
-                docker push ${ECR_URI}:${IMAGE_TAG}
+                docker push ${PUBLIC_ECR_URI}:${IMAGE_TAG}
+                docker push ${PUBLIC_ECR_URI}:${IMAGE_NAME}-latest
                 '''
             }
         }
@@ -81,10 +81,10 @@ pipeline {
         stage('Update Manifest') {
             steps {
                 sh '''
-                sed -i "s|ghcr.io/open-telemetry/demo:1.12.0-cartservice|${ECR_URI}:${IMAGE_TAG}|g" \
+                sed -i "s|image:.*|image: ${PUBLIC_ECR_URI}:${IMAGE_TAG}|g" \
                 src/cart/kubernetes/cart/deploy.yaml
 
-                echo "Updated Images:"
+                echo "Updated Image:"
                 grep -n "image:" src/cart/kubernetes/cart/deploy.yaml
                 '''
             }
@@ -102,7 +102,9 @@ pipeline {
         stage('Rollout Status') {
             steps {
                 sh '''
-                kubectl rollout status deployment/${K8S_DEPLOYMENT} -n ${NAMESPACE}
+                kubectl rollout status deployment/${K8S_DEPLOYMENT} \
+                -n ${NAMESPACE} \
+                --timeout=300s
                 '''
             }
         }
@@ -111,16 +113,17 @@ pipeline {
     post {
 
         success {
-            echo 'Cart Service Deployment Successful'
+            echo "Cart Service Deployment Successful"
+            echo "Image Pushed: ${PUBLIC_ECR_URI}:${IMAGE_TAG}"
         }
 
         failure {
-            echo 'Pipeline Failed'
+            echo "Pipeline Failed"
         }
 
         always {
             sh '''
-            docker image prune -f || true
+            docker image prune -af || true
             '''
         }
     }
